### PR TITLE
Make FunctionRegistry enumerable.

### PR DESCRIPTION
**Pull request by mibe**
Mostly copy&paste from ConstantRegistry.

### CODE REVIEW

**Comment by pieterderycke** [comment]
Before I accept the pull request: could you explain me why you need this modification?

**Comment by mibe** [comment]
Sure. I should have added some more info before. Sorry about that.

I had the requirement to display the available functions and constants to the user (see [here](https://i.imgur.com/RyPtdEt.png)). I had to implement a hack using reflection to gain access to the registries. `ConstantRegistry` inherits `IEnumerable<>` already (so this was straight forward), but `FunctionRegistry` does not, so I thought, why not implement it for `FunctionRegistry` also.

But what still is missing for this requirement is actually access to both registries in `CalculationEngine`. Maybe make the properties `FunctionRegisty` & `ConstantRegistry` public instead of internal?

Here's the hack I'm currently using with version 0.8.7:

```csharp
public static IEnumerable<ConstantInfo> GetConstants(CalculationEngine engine)
{
	return (ConstantRegistry)getProperty(engine, "ConstantRegistry");
}
		
public static IEnumerable<FunctionInfo> GetFunctons(CalculationEngine engine)
{
	FunctionRegistry registry = (FunctionRegistry)getProperty(engine, "FunctionRegistry");
	Dictionary<string, FunctionInfo> functions = (Dictionary<string, FunctionInfo>)getField(registry, "functions");
	return functions.Select(x => x.Value);
}

private static object getProperty(object @object, string propertyName)
{
	PropertyInfo property = @object.GetType().GetProperty(propertyName, BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.GetProperty);
	return property.GetValue(@object);
}

private static object getField(object @object, string fieldName)
{
	FieldInfo field = @object.GetType().GetField(fieldName, BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.GetField);
	return field.GetValue(@object);
}
```

**Comment by mibe** [comment]
On the other hand, instead of making the registries public, a single property returning the functions / constants would be enough (at least for me :wink:):

```csharp
public IEnumerable<string> AvailableFunctions
{
    get { return FunctionRegistry.Select(x => x.FunctionName); }
}
```

**Comment by pieterderycke** [comment]
Ok, you have a valid requirement 🙂 You can expect the feature in the comming days in the dev branch. I will nog expose an IEnumerale<String> but IEnumerable<FunctionInfo> so that you can also know the number of parameters of a function.

Btw: Jace 0.9 will also support functions with a dynamic number of arguments Max(1,2,...,n) instead of Max(1,2)
Btw: .Net Core will be supported 🙂

**Pull request closed without merging**
